name: Cross Platform Cargo Check

on:
  workflow_dispatch:
#   pull_request:
#   push:
# branches: [main, dev]

permissions:
  contents: read

env:
  HUSKY: 0

jobs:
  cargo-check:
    # Treat all Rust compiler warnings as errors
    env:
      RUSTFLAGS: '-D warnings'
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      - name: Add Rust Target
        run: rustup target add aarch64-apple-darwin

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: '24.15.0'

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          run_install: false

      - name: Pnpm install and check
        run: |
          pnpm i
          pnpm run prebuild aarch64-apple-darwin

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri
          save-if: false

      - name: Cargo Check (deny warnings)
        working-directory: src-tauri
        run: |
          cargo check --target aarch64-apple-darwin --workspace --all-features
