name: Development Test

on:
  workflow_dispatch:

permissions: write-all
env:
  TAG_NAME: deploytest
  TAG_CHANNEL: DeployTest
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short
  HUSKY: 0
concurrency:
  group: '${{ github.workflow }} - ${{ github.head_ref || github.ref }}'
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  dev:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@1.91.0

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
          prefix-key: 'v1-rust'
          key: 'rust-shared-stable-macos-aarch64-apple-darwin'
          workspaces: |
            . -> target
          cache-all-crates: true
          cache-workspace-crates: true

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: '24.15.0'
          cache: 'pnpm'

      - name: Pnpm Cache
        uses: actions/cache@v5
        with:
          path: ~/.pnpm-store
          key: 'pnpm-shared-stable-macos-aarch64-apple-darwin'
          restore-keys: |
            pnpm-shared-stable-macos-aarch64-apple-darwin
          lookup-only: true

      - name: Pnpm install and check
        run: |
          pnpm i
          pnpm run prebuild aarch64-apple-darwin

      - name: Release ${{ env.TAG_CHANNEL }} Version
        run: pnpm release-version ${{ env.TAG_NAME }}

      - name: Add Rust Target
        run: |
          rustup target add aarch64-apple-darwin --toolchain 1.91.0 || rustup target add aarch64-apple-darwin
          rustup target list --installed

      - name: Tauri build
        uses: tauri-apps/tauri-action@v0
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        with:
          tauriScript: pnpm
          args: --target aarch64-apple-darwin -b dmg

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: target/aarch64-apple-darwin/release/bundle/dmg/*.dmg
          if-no-files-found: error
